AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch an instances with individually selectable AMI, instance type, subnet, keypair, and security group.
  Volumes encrypted using a shared KMS key. Termination protection is enabled. No custom tags—uses tags from AMI.

Parameters:
  InstanceProfile:
    Type: String
    Description: "Select an IAM Instance Profile to attach to EC2 instances"
    Default: "None"
    AllowedValues:
      - "None"
      - "EC2-SSM"

  InstanceName1:
    Type: String
    Description: "Name tag for EC2 Instance 1"
    Default: "MyInstance-1"

  InstanceName2:
    Type: String
    Description: "Name tag for EC2 Instance 1"
    Default: "MyInstance-2"

  # AMI 1
  AMI1:
    Type: String
    Default: "None"
    AllowedValues:
      - "None"
      - "ami-0da76921de4be3a45"
    Description: "Select AMI 1"

  InstanceType1:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - r5.xlarge
      - c5.large
    Description: "Instance type for Instance 1"

  KeyPair1:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Key pair for Instance 1"

  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet for Instance 1"

  SecurityGroup1:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security group for Instance 1"

  # AMI 2
  AMI2:
    Type: String
    Default: "None"
    AllowedValues:
      - "None"
      - "ami-0da76921de4be3a45"
    Description: "Select AMI 2"

  InstanceType2:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - r5.xlarge
      - c5.large
    Description: "Instance type for Instance 2"

  KeyPair2:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Key pair for Instance 2"

  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet for Instance 2"

  SecurityGroup2:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security group for Instance 2"

Conditions:
  LaunchInstance1: !Not [!Equals [!Ref AMI1, "None"]]
  LaunchInstance2: !Not [!Equals [!Ref AMI2, "None"]]

Resources:

  EC2Instance1:
    Type: AWS::EC2::Instance
    Condition: LaunchInstance1
    Properties:
      ImageId: !Ref AMI1
      InstanceType: !Ref InstanceType1
      KeyName: !Ref KeyPair1
      SubnetId: !Ref SubnetId1
      SecurityGroupIds:
        - !Ref SecurityGroup1
      IamInstanceProfile: !Ref InstanceProfile
      DisableApiTermination: true
      Tags:
        - Key: Name
          Value: !Ref InstanceName1
      MetadataOptions:
        HttpTokens: required
        HttpPutResponseHopLimit: 2

  EC2Instance2:
    Type: AWS::EC2::Instance
    Condition: LaunchInstance2
    Properties:
      ImageId: !Ref AMI2
      InstanceType: !Ref InstanceType2
      KeyName: !Ref KeyPair2
      SubnetId: !Ref SubnetId2
      SecurityGroupIds:
        - !Ref SecurityGroup2
      IamInstanceProfile: !Ref InstanceProfile
      DisableApiTermination: true
      Tags:
        - Key: Name
          Value: !Ref InstanceName2
      MetadataOptions:
        HttpTokens: required
        HttpPutResponseHopLimit: 2

Outputs:
  Instance1Id:
    Condition: LaunchInstance1
    Value: !Ref EC2Instance1

  Instance2Id:
    Condition: LaunchInstance2
    Value: !Ref EC2Instance2